baseURL = "https://thumbler.dev/"
languageCode = "en-us"
title = "thumbler.dev"
theme = "lanyon-hugo"
publishDir = "docs"

[params]
    title = "thumbler.dev"
    description = "a hacking blog"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
